window.addEventListener('DOMContentLoaded', event => {

    // Navbar shrink function
    var navbarShrink = function () {
        const navbarCollapsible = document.body.querySelector('#mainNav');
        if (!navbarCollapsible) {
            return;
        }
        if (window.scrollY === 0) {
            navbarCollapsible.classList.remove('navbar-shrink')
        } else {
            navbarCollapsible.classList.add('navbar-shrink')
        }

    };

    // Shrink the navbar 
    navbarShrink();

    // Shrink the navbar when page is scrolled
    document.addEventListener('scroll', navbarShrink);

    //  Activate Bootstrap scrollspy on the main nav element
    const mainNav = document.body.querySelector('#mainNav');
    if (mainNav) {
        new bootstrap.ScrollSpy(document.body, {
            target: '#mainNav',
            rootMargin: '0px 0px -0%',
        });
    };

    // Collapse responsive navbar when toggler is visible
    const navbarToggler = document.body.querySelector('.navbar-toggler');
    const responsiveNavItems = [].slice.call(
        document.querySelectorAll('#navbarResponsive .nav-link')
    );
    responsiveNavItems.map(function (responsiveNavItem) {
        responsiveNavItem.addEventListener('click', () => {
            if (window.getComputedStyle(navbarToggler).display !== 'none') {
                navbarToggler.click();
            }
        });
    });

});

function menuBtnFunction(menuBtn) {
    menuBtn.classList.toggle("active");
}
// const translations = {
//     en: {
//         home: "Home",
//         trips: "Trips",
//         hotels: "Hotels",
//         cityTours: "City Tours",
//         travels: "Travels",
//         about: "About",
//         contact: "Contact",
//         bookNow: "Book Now",
//         mastheadTitle: "Your Best Choice",
//         contactUs: "Contact Us",
//         contactSubheading: "We are at your service. Do not hesitate to contact us",
//         // Add more translations as needed
//     },
//     ar: {
//         home: `الصفحة الرئيسية  `,
//         trips: "الرحلات",
//         hotels: "الفنادق",
//         cityTours: "جولات المدينة",
//         travels: "السفر",
//         about: "حول",
//         contact: "تواصل",
//         bookNow: "احجز الآن",
//         mastheadTitle: "خيارك الأفضل",
//         contactUs: "اتصل بنا",
//         contactSubheading: "نحن في خدمتك. لا تتردد في الاتصال بنا",
//         boat: "رحلات القارب",
//         safari: "رحلات السفاري",
//         diving: "رحلات الغطس",
//         // Add more translations as needed
//     },
//     ru: {
//         home: "Главная",
//         trips: "Поездки",
//         hotels: "Отели",
//         cityTours: "Городские туры",
//         travels: "Путешествия",
//         about: "О нас",
//         contact: "Контакт",
//         bookNow: "Забронировать",
//         mastheadTitle: "Ваш лучший выбор",
//         contactUs: "Свяжитесь с нами",
//         contactSubheading: "Мы к вашим услугам. Не стесняйтесь обращаться к нам",
//         // Add more translations as needed
//     }
// };

// function changeLanguage(lang) {
//     document.querySelector('.nav-link[href="index.html"]').textContent = translations[lang].home;
//     document.querySelector('.nav-link[href="Hotels.html"]').textContent = translations[lang].hotels;
//     document.querySelector('.nav-link[href="citytours.html"]').textContent = translations[lang].cityTours;
//     document.querySelector('.nav-link[href="travels.html"]').textContent = translations[lang].travels;
//     document.querySelector('.nav-link[href="About.html"]').textContent = translations[lang].about;
//     document.querySelector('.nav-link[href="#contact"]').textContent = translations[lang].contact;
//     document.querySelector('.nav-link[href="trips/boattrips.html"]').textContent = translations[lang].boat;
//     document.querySelector('.nav-link[href="trips/safari.html"]').textContent = translations[lang].safari;
//     document.querySelector('.nav-link[href="trips/diving.html"]').textContent = translations[lang].diving;
//     document.querySelector('#trips').innerText = translations[lang].trips;

//     // Add more elements to update as needed
// }

document.querySelectorAll('.btn-book').forEach(button => {
    button.addEventListener('click', function () {
        const modalId = this.getAttribute('data-modal');
        const modal = document.getElementById(modalId);
        modal.style.display = 'block';
    });
});

document.querySelectorAll('.close').forEach(span => {
    span.addEventListener('click', function () {
        document.querySelectorAll('.modal').forEach(modal => {
            modal.style.display = 'none';
        });
    });
});

window.onclick = function (event) {
    if (event.target.classList.contains('modal')) {
        event.target.style.display = 'none';
    }
}


function showPopup() {
    const popup = document.getElementById('help-popup')
    const popupbg = document.getElementById('pop-up-bg')
    popupbg.style.display = "block"
    popup.style.display = 'block'
}

function closePopup() {
    const popup = document.getElementById('help-popup')
    popup.style.display = 'none'
    const popupbg = document.getElementById('pop-up-bg')
    popupbg.style.display = "none"
}

setInterval(showPopup, 120000);

document.getElementById('close-popup').addEventListener('click', closePopup);


const translations = {
 
    ru: {
        "help-text": "Jeśli nie znalazłeś tego, czego szukasz, nie wahaj się do nas napisać, a pomożemy Ci tak szybko, jak to możliwe!",
        "send-whatsapp-btn": "Wyślij WhatsApp",
        "call-or-whatsapp": "Zadzwoń lub WhatsApp: +201552378066",
        "home": "Strona główna",
        "trips": "Wycieczki",
        "boat-trips": "Rejsy łodzią",
        "safari": "Safari",
        "diving": "Nurkowanie",
        "hotels": "Hotele",
        "city-tours": "Wycieczki po mieście",
        "hurghada": "Hurghada",
        "el-gouna": "El Gouna",
        "travels": "Podróże",
        "about": "O nas",
        "language": "Język",
        "english": "Angielski",
        "russian": "polszczyzna",
        "carousel-title": "ALBATROS MORZE CZERWONE",
        "carousel-subtitle": "Najlepsze nad Morzem Czerwonym",
        "welcome": "Witamy w Albatros Travel",
        "intro-text": "Rezerwuj swoje wycieczki w Egipcie online. Oferujemy szeroki wybór wycieczek i atrakcji w Egipcie oraz bilety do najpopularniejszych zabytków. Działamy w Egipcie i specjalizujemy się w wakacjach egipskich, wycieczkach i jednodniowych wyprawach w całym Egipcie.",
        "free-cancellation": "Bezpłatne anulowanie",
        "no-coffee-trip": "Brak wycieczek sprzedażowych",
        "high-quality-services": "Usługi wysokiej jakości",
        "best-price-guarantee": "Gwarancja najlepszej ceny",
        "insurance-included": "Ubezpieczenie w cenie",
        "Boat Trips": "Rejsy łodzią",
        "Safari": "Safari",
        "Diving": "Nurkowanie",
        "Cairo": "Kair",
        "Luxor": "Luksor",
        "Sea Activity": "Aktywności morskie",
        "excursions": "Wycieczki z Hurghady, El Gouny, Makadi",
        "luxorPrivate": "Prywatna wycieczka do Luksoru",
        "luxorTwoDays": "Luksor na dwa dni, prywatnie",
        "cairoPrivate": "Prywatna wycieczka do Kairu",
        "cairoDayTrip": "Jednodniowa wycieczka do Kairu samolotem",
        "cairoTwoDays": "Kair na dwa dni, prywatnie",
        "cairoExclusive": "Ekskluzywna jednodniowa wycieczka do Kairu na życzenie",
        "cairoPyramids": "Kair: Piramidy w Gizie, Sakkara i Dahszur, ekskluzywnie",
        "denderaHalfDay": "Półdniowa wycieczka do Dendery",
        "denderaAbydos": "Prywatna jednodniowa wycieczka do Dendery i Abydos",
        "hurghadaCityTour": "Zwiedzanie Hurghady",
        "elGounaCityTour": "Zwiedzanie El Gouny",
        "aswanAbuSimbel": "Asuan i Abu Simbel na dwa dni, prywatnie",
        "monasteries": "Klasztory św. Antoniego i św. Pawła",
        "quadTour3Hours": "3-godzinna wycieczka quadem + jazda na wielbłądzie",
        "quadTour5Hours": "5-godzinna wycieczka quadem + jazda na wielbłądzie + kolacja",
        "egyptDayTours": "Jednodniowe wycieczki i wyjazdy po Egipcie z Hurghady",
        "varietyAndFun": "Od wycieczek klasztornych po zwiedzanie Hurghady; oferujemy wiele różnorodności i zabawy dla całej rodziny.",
        "luxorTriptitle": "Wycieczka do Luksoru",
        "luxorTripdescription": "Wycieczka do Luksoru",
        "luxorTripprice": "60.00 EUR",
        "cairoTriptitle": "Wycieczka do Kairu",
        "cairoTripdescription": "Wycieczka do Kairu",
        "cairoTripprice": "70.00 EUR",
        "hurghadaTriptitle": "Wycieczka do Hurghady",
        "hurghadaTripdescription": "Wycieczka do Hurghady",
        "hurghadaTripprice": "20.00 EUR",
        "moreDetails": "Więcej szczegółów",
        "paradise_island": "WYSPA RAJU",
        "best_price": "Najlepsza cena za osobę",
        "your_favourite_trip": "Twoja ulubiona wycieczka!",
        "duration": "• Czas trwania",
        "snorkelling": "• Snurkowanie + sprzęt",
        "drinks_and_lunch": "• Napoje bezalkoholowe i gorąca herbata oraz obiad na pokładzie",
        "pickup": "• Odbiór i powrót do hotelu",
        "book_now": "Rezerwuj teraz",
        "more_details": "Więcej szczegółów",
        "desert_safari": "Safari pustynne",
        "quad_3h": "3-godzinna wycieczka quadem",
        "exciting_experience": "• Ekscytujące doświadczenie na quadzie",
        "bedouin_village": "• Wizyta w wiosce Beduinów na pustyni",
        "camels_ride": "• Jazda na wielbłądzie",
        "desert_safari_sunset": "Safari pustynne o zachodzie słońca",
        "dinner_party": "• Kolacja + impreza",
        "desert_mega_safari": "Mega Safari na pustyni",
        "hurghadaTitle": "Zwiedzanie Hurghady",
        "bestPrice": "Najlepsza cena za osobę",
        "hurghadaPrice": "15 EUR",
        "hurghadaTitleCard": "Zwiedzanie Hurghady",
        "hurghadaDescription": "Hurghada: poranne lub wieczorne wycieczki z przewodnikiem. Przewodnik angielsko-/niemieckojęzyczny.",
        "duration": "• 3 godziny",
        "groupSize": "• Mała grupa",
        "returnTrip": "• Podróż w obie strony",
        "mosqueVisit": "• Wizyta w największym meczecie",
        "churchVisit": "• Wizyta w największym kościele",
        "oldCity": "• Stare miasto",
        "shishaExtra": "• Shisha + 5 EUR ekstra (rodzaj shishy lub fajka wodna)",
        "bookNow": "Rezerwuj teraz",
        "horseRiding": "Jazda konna",
        "horseRidingTitle": "Jazda konna + pływanie",
        "horsePrice1Hour": "1 godzina = 30 EUR",
        "horsePrice2Hour": "2 godziny = 50 EUR",
        "horsePrice3Hour": "3 godziny = 70 EUR",
        "horseRidingTitleCard": "Jazda konna + pływanie",
        "horseDescription": "Twoja ulubiona przejażdżka",
        "horseDuration": "• 1, 2 lub 3 godziny",
        "horseEveryDay": "• Codziennie",
        "hotelPickup": "• Możliwy odbiór z hotelu",
        "nativeSpeaker": "• Przewodnik w języku ojczystym",
        "moreDetails": "Więcej szczegółów",
        "camel_riding": "Jazda na wielbłądzie",
        "best_price": "Najlepsza cena za osobę",
        "price_1hour": "1 godzina = 30 EUR",
        "price_2hour": "2 godziny = 50 EUR",
        "price_3hour": "3 godziny = 70 EUR",
        "card_title": "Jazda na wielbłądzie",
        "favourite_ride": "Twoja ulubiona przejażdżka",
        "duration": "• 1, 2 lub 3 godziny",
        "every_day": "• Codziennie",
        "hotel_pickup": "• Możliwy odbiór z hotelu",
        "native_speaker": "• Przewodnik w języku ojczystym",
        "book_now": "Rezerwuj teraz",
        "more_details": "Więcej szczegółów",
        "time": "Czas",
        "program": "Program",
        "time_1430": "⏰ 14:30",
        "time_1500": "⏰ 15:00",
        "time_1900": "⏰ 19:00",
        "pick_up": "Odbiór z hotelu",
        "arrival_safari": "Przyjazd na stację safari",
        "back_hotel": "Powrót do hotelu",
        "description_5hours": "Opis 5-godzinnej wycieczki quadem i jazdy na wielbłądzie",
        "quad_pickup": "Odbierzemy Cię około 14:30 z hotelu i zawieziemy na stację quadów...",
        "quad_instructions": "Wszystkie quady są wyposażone w automatyczny system sterowania, wystarczy używać gazu i hamulca...",
        "quad_drive": "Jedziemy około 1 godziny (ok. 25 km) quadem, aż dotrzemy do wioski Beduinów...",
        "bedouin_village": "Przyjaźni Beduini powitają Cię w swojej wiosce...",
        "camel_ride": "Tutaj będziesz mieć możliwość jazdy na wielbłądzie i zwiedzania okolicy...",
        "back_to_hotel": "Następnie odwieziemy Cię z powrotem do hotelu.",
        "dinner_bqq": "Kolacja + BBQ Party + pokaz tańca + pokaz ognia",
        "time_1130": "⏰ 11:30",
        "time_1200": "⏰ 12:00",
        "description_mega_safari": "Opis Mega Safari",
        "mega_safari_details": "• 1 godzina jazdy quadem <br> • 20 minut jazdy buggy jeepem <br> • Herbata, jazda na wielbłądzie...",
        "paradise_snorkeling": "Jednodniowa wycieczka snorkelingowa na wyspę Paradise",
        "snorkeling_description_1": "Ciesz się niezapomnianym pływaniem na prywatnej plaży wyspy Paradise i relaksującym rejsem po Morzu Czerwonym...",
        "snorkeling_description_2": "Wyspa Paradise to rezerwat przyrody na Morzu Czerwonym w pobliżu Hurghady, oferujący odwiedzającym białe piaszczyste plaże...",
        "snorkeling_description_3": "Pływaj i snurkuj z wieloma egzotycznymi rybami i odkryj unikalny podwodny świat...",
        "paradise_program": "Program jednodniowej wycieczki snorkelingowej na wyspę Paradise",
        "boat_trip": "Rejs łodzią ze snorkelingiem",
        "island_stay": "Pobyt na wyspie",

      "folklore_show": "Pokaz folklorystyczny",
      "paradise_description": "Opis wycieczki jednodniowej na snorkeling na wyspie Paradise",
      "paradise_snorkeling_program_1": "Odbierzemy Cię z hotelu klimatyzowanym samochodem i zawieziemy do portu, gdzie rozpocznie się Twoja przygoda ze snorkelingiem...",
      "paradise_snorkeling_program_2": "Podziwiaj kolorowe koralowce i pływaj z różnorodnymi egzotycznymi rybami...",
      "paradise_snorkeling_program_3": "Po przystanku na snorkeling popłyniemy dalej na wyspę Paradise...",
      "safari_title": "Safari quadami i przejażdżka na wielbłądzie",
      "safari_desc1": "Ta 3-godzinna wycieczka to zakurzone, ale gwarantowane wrażenia i świetna zabawa!",
      "safari_desc2": "3-godzinne safari quadami to świetna okazja, aby doświadczyć pustyni w całej jej okazałości i majestacie. To wycieczka dla tych, którzy chcą przemierzać pustynię na czterokołowym quadzie.",
      "safari_desc3": "Podczas safari możesz poznać życie i tradycje wioski Beduinów, przejechać się na wielbłądzie i dowiedzieć się ciekawych faktów o ich życiu na pustyni.",
      "safari_desc4": "Wspomnienia i wrażenia z tej wycieczki pozostaną z Tobą na długo!",
      "safari_program_title": "Program 3-godzinnego safari quadami i przejażdżki na wielbłądzie",
      "time": "Czas",
      "program": "Program",
      "safari_time1": "⏰ 7:30",
      "safari_prog1": "Odbiór z hotelu",
      "safari_time2": "⏰ 8:00",
      "safari_prog2": "Przyjazd do stacji safari",
      "safari_time3": "⏰ 11:00",
      "safari_prog3": "Powrót do hotelu",
      "safari_time4": "⏰ 11:30",
      "safari_prog4": "Przyjazd do hotelu",
      "safari_desc_title": "Opis 3-godzinnego safari quadami i przejażdżki na wielbłądzie",
      "safari_desc5": "Odbierzemy Cię około godziny 07:30 z hotelu i zawieziemy na stację treningową...",
      "safari_desc6": "Wszystkie quady są wyposażone w automatyczny system sterowania...",
      "safari_desc7": "Jedziemy około godzinę (ok. 25 km), aż dotrzemy do wioski Beduinów.",
      "safari_desc8": "Przywitają Cię przyjaźni Beduini...",
      "safari_desc9": "W tym miejscu będziesz mieć okazję przejechać się na wielbłądzie...",
      "safari_desc10": "Następnie odwieziemy Cię z powrotem do hotelu.",
      "city_tour_title": "Prywatna wycieczka po Hurghadzie",
      "city_tour_desc1": "Chcesz poznać prawdziwą, oryginalną Hurghadę?",
      "city_tour_desc2": "Wybraliśmy dla Ciebie odpowiednią mieszankę...",
      "city_tour_program_title": "Program prywatnej wycieczki po Hurghadzie",
      "city_tour_stop1": "Meczet El-Mina Masjid",
      "city_tour_stop2": "Katedra koptyjska św. Shenoudy",
      "city_tour_stop3": "Targ rybny",
      "city_tour_stop4": "Targ warzywny",
      "city_tour_stop5": "Bulwar Hurghada Marina",
      "city_tour_desc_title": "Opis prywatnej wycieczki po Hurghadzie",
      "city_tour_desc3": "Odbierzemy Cię z hotelu o godzinie 14:00...",
      "city_tour_desc4": "Pierwszy przystanek zaprowadzi Cię bezpośrednio na najwyższy punkt...",
      "city_tour_desc5": "Następnie pojedziemy dalej do miejskiego molo...",
      "city_tour_desc6": "Kontynuujemy wycieczkę na targu rybnym...",
      "city_tour_desc7": "Jeśli masz specjalne życzenie...",
      "city_tour_desc8": "Około godziny 19:00 odwieziemy Cię z powrotem do hotelu...",
      "included_services_title": "Usługi w cenie",
      "included_service1": "Odbiór z hotelu",
      "included_service2": "Przewodnik mówiący po angielsku",
      "included_service3": "Całodobowa obsługa klienta",
      "included_service4": "Ubezpieczenie w cenie",
      "prices_title": "Ceny",
      "people": "Liczba osób",
      "vehicle": "Transport",
      "price_per_adult": "Cena za osobę",
      "price1_people": "1-2 osoby",
      "price1_vehicle": "Samochód prywatny",
      "price1_amount": "15 € za osobę",
      "price2_people": "4-5 osób",
      "price2_vehicle": "Prywatny minibus",
      "price2_amount": "10 € za osobę",
      "duration": "Czas trwania",
      "trip_type": "Rodzaj wycieczki",
      "availability": "Dostępność",
      "pickup_time": "Godzina odbioru",
      "duration_value": "ok. 6 godzin",
      "trip_type_value": "Indywidualna",
      "availability_value": "Codziennie",
      "pickup_time_value": "ok. 14:00",
      "ride_on_horseback": "Przejażdżka konna przez pustynię i wzdłuż plaży",
      "horseback_description": "Jedź konno przez pustynię i wzdłuż plaży, aby odkryć wielkie cuda natury Hurghady podczas tej przygody.",
      "itinerary": "Plan podróży",
      "itinerary_description": "Odbierzemy Cię z hotelu. Rozpocznij swój dzień przejażdżką konną pod okiem profesjonalnego trenera. Jedź godzinę przez pustynię i kolejną godzinę wzdłuż plaży. Podczas jazdy wzdłuż morza podziwiaj zapierające dech w piersiach widoki i twórz niezapomniane wspomnienia w wyjątkowym otoczeniu.",
      "what_to_expect": "Czego się spodziewać",
      "beginner_info": "Nie martw się, jeśli jesteś początkujący, zapewniamy kaski, a trener pomoże Ci w razie potrzeby.",
      "egyptian_horse": "Skorzystaj z rzadkiej okazji jazdy na egipskim koniu nad morzem i na pustyni",
      "explore_desert": "Odkrywaj pustynię konno",
      "play_in_sea": "Baw się ze swoim koniem w morzu",
      "transfer_information": "Informacje o transferze",
      "transfer_details": "Transfer z każdego hotelu w Hurghadzie jest bezpłatny. Transfer z (Sahl Hasheesh, Makadi Bay, El Gouna) kosztuje dodatkowo 5 € za osobę, a z (Soma Bay, Safaga) 10 € za osobę.",
      "suitability_warning": "Nieodpowiednie dla kobiet w ciąży i osób z problemami kręgosłupa",
      "ride_on_camelback": "Przejażdżka na wielbłądzie przez pustynię i wzdłuż plaży",
      "camelback_description": "Jazda na wielbłądzie przez pustynię i wzdłuż plaży, aby odkryć wielkie cuda natury Hurghady podczas tej przygody.",
      
      "special_features": "Nasze szczególne cechy",
      "special_features_description": "Urlop to prawdopodobnie najcenniejszy czas w roku dla każdego. Dlatego przykładamy dużą wagę do tego, aby zapewnić Ci ciekawy i relaksujący czas.",
      "who_we_are": "Kim jesteśmy",
      "individual_excursions": "Indywidualne wycieczki w Egipcie",
      "individual_excursions_description": "Odwiedzamy nie tylko najciekawsze zabytki, ale także pokazujemy Ci to, co leży poza utartymi szlakami.",
      "fair_prices": "Uczciwe ceny / Brak dodatkowych kosztów",
      "fair_prices_description": "Oferujemy wysoką jakość i indywidualną obsługę w przystępnych cenach.",
      "time_for_you": "Czas dla Ciebie",
      "time_for_you_description": "Dzięki małej wielkości grupy masz wystarczająco dużo czasu, aby zobaczyć wszystko we własnym tempie.",
      "adapt_to_you": "Dostosowujemy się do Ciebie",
      "adapt_to_you_description": "Większość naszych wycieczek można dostosować do Twojego harmonogramu i potrzeb.",
      "contact_us": "Skontaktuj się z nami",
      "contact_description": "Jesteśmy do Twojej dyspozycji. Nie wahaj się z nami skontaktować",
      "your_name": "Twoje imię",
      "name_required": "Imię jest wymagane.",
      "your_email": "Twój e-mail",
      "email_required": "E-mail jest wymagany.",
      "email_invalid": "E-mail jest nieprawidłowy.",
      "your_phone": "Twój numer telefonu",
      "phone_required": "Numer telefonu jest wymagany.",
      "your_message": "Twoja wiadomość",
      "message_required": "Wiadomość jest wymagana.",
      "form_successful": "Formularz został pomyślnie wysłany!",
      "form_error": "Błąd podczas wysyłania wiadomości!",
      "send_message": "Wyślij wiadomość",
      "copyright": "Prawa autorskie &copy; ALBATROS TRAVEL 2024",
      "travelLuxor": "Luksor",
      "travelPriceForPerson": "Najlepsza cena za osobę",
      "travelPrice60EUR": "60.00 EUR",
      "travelTitleLuxor": "Wycieczka do Luksoru",
      "travelFavoriteTrip": "Twoja ulubiona podróż!",
      "travelDuration1Day": "• Czas trwania 1 dzień",
      "travelBus": "• Transport klimatyzowanym autobusem",
      "travelWithEntry": "• z wejściem",
      "travelWaterOnBoard": "• Woda na pokładzie",
      "travelBookNow": "Zarezerwuj teraz",
      "travelMoreDetails": "Więcej szczegółów",
      "travelCairo": "Kair",
      "travelPrice70EUR": "70.00 EUR",
      "travelTitleCairo": "Wycieczka do Kairu",
      "travelVehicle": "• Transport klimatyzowanym pojazdem",
      "travelWithEntryPickup": "• z wejściem, odbiorem i dostawą w Kairze/Gizie",
      "travelProgramLuxorTour": "Program prywatnej wycieczki do Luksoru",
      "travelKarnakTemple": "Świątynia w Karnaku",
      "travelColossiMemnon": "Kolosy Memnona",
      "travelHatshepsutTemple": "Świątynia grobowa Hatszepsut",
      "travelValleyKings": "Dolina Królów",
      "travelLunch": "Obiad (potrawy egipskie)",
      "travelNileExcursion": "Rejs po Nilu trwa 1 godzinę (TYLKO U NAS ZA DARMO)",
      "travelDescriptionLuxorTour": "Opis prywatnej wycieczki do Luksoru",
      "travelPickedMorning": "Zostaniesz odebrany wcześnie rano. Następnie pojedziesz nowoczesnym, komfortowym i klimatyzowanym pojazdem przez Safagę nowo wybudowaną drogą pustynną około 225 km do doliny Nilu w Qena.",
      "travelShortBreak": "Po drodze zrobisz krótką przerwę, aby skorzystać z toalety lub rozprostować nogi.",
      "travelDriveToLuxor": "Następnie pojedziesz gęsto zaludnioną drogą krajową do Luksoru (ok. 60 km).",
      "travelArrivalLuxor": "Po przybyciu do Luksoru rozpoczniesz zwiedzanie. Najpierw odwiedzisz największy kompleks świątynny na świecie z ogromną salą kolumnową. Autobus zawiezie Cię na zachodnią stronę Luksoru, gdzie zjesz obiad w typowej egipskiej kawiarni.",
      "travelValleyKingsTour": "Po przerwie obiadowej zwiedzisz słynną Dolinę Królów z przewodnikiem po królewskich grobowcach. Nowość! Teraz dozwolone jest darmowe fotografowanie grobowców telefonem komórkowym bez lampy błyskowej. Następnie odwiedzisz taras świątyni Hatszepsut, popularne miejsce do robienia zdjęć. Twoja wycieczka zakończy się przy imponujących Kolosach Memnona.",
      "travelReturnToHurghada": "Następnie wrócisz do Hurghady. Czas, aby przemyśleć wrażenia dnia i może obserwować życie nad Nilem. Około godziny 20:00 zostaniesz odwieziony do hotelu. Wycieczka do Luksoru i Doliny Królów na długo pozostanie w Twojej pamięci.",
      "travelPrices": "Ceny",
      "travelNumberOfPeople": "Liczba osób",
      "travelVehicle": "Pojazd",
      "travelPricePerAdult": "Cena za osobę dorosłą",
      "travelTwoPersons": "2 osoby",
      "travelPrivateCar": "Samochód prywatny",
      "travel125": "125 € za osobę",
      "travelFourPersons": "4 osoby",
      "travelPrivateMiniBus": "Prywatny minibus",
      "travel100": "100 € za osobę",
      "travelSixToEightPersons": "6 - 8 osób",
      "travel80": "80 € za osobę",
      "travelPrivateLuxorTour": "Program prywatnej wycieczki do Luksoru",
      "travelKarnakTemple": "Świątynia w Karnaku",
      "travelColossiMemnon": "Kolosy Memnona",
      "travelTempleHatshepsut": "Świątynia grobowa Hatszepsut",
      "travelValleyOfKings": "Dolina Królów",
      "travelLunch": "Obiad (potrawy egipskie)",
      "travelNileExcursion": "Rejs po Nilu trwa 1 godzinę (TYLKO U NAS ZA DARMO)",
      "travelDescriptionLuxorTour": "Opis prywatnej wycieczki do Luksoru",
      "travelPickUp": "Zostaniesz odebrany wcześnie rano...",
      "travelShortBreak": "Po drodze robimy krótką przerwę...",
      "travelDriveLuxor": "Następnie jedziemy gęsto zaludnioną...",
      "travelArrivalLuxor": "Po przybyciu do Luksoru...",
      "travelLunchBreak": "Po przerwie obiadowej...",
      "travelReturnHurghada": "Po wycieczce wracamy do Hurghady...",
      "travelCairoTour": "Program prywatnej wycieczki do Kairu",
      "travelEgyptianMuseum": "Muzeum Egipskie...",
      "travelPyramids": "Piramidy w Gizie",
      "travelSphinx": "Wielki Sfinks w Gizie",
      "travelValleyTempleKhafre": "Świątynia Dolinna Chefrena",
      "travelOldTown": "Stare Miasto Kair (tylko u nas)",
      "travelBazaar": "Bazaar Khan el-Khalili (tylko u nas)",
      "travelSightseeing": "Zwiedzanie miasta",
      "travelLunchCairo": "Obiad",
      "travelDescriptionCairoTour": "Opis prywatnej wycieczki do Kairu",
      "travelPickUpCairo": "Odbierzemy Cię z hotelu o 3:00...",
      "travelShortBreakCairo": "Około 5:30 robimy krótką przerwę...",
      "travelArrivalCairo": "Docieramy do Kairu około 8:00...",
      "travelEgyptianMuseumTour": "Następnie odwiedzamy Muzeum Egipskie...",
      "travelLunchLocalDishes": "Następnie spróbujesz lokalnych egipskich potraw...",
      "travelVisitGiza": "Po obiedzie odwiedzamy Piramidy...",
      "travelReturnHurghadaCairo": "Wracamy do Hurghady około 20:00...",
      
      "travel-luxor-title": "Luksor",
      "travel-luxor-best-price": "Najlepsza cena za osobę",
      "travel-luxor-price": "60.00 EUR",
      "travel-luxor-card-title": "Podróż do Luksoru",
      "travel-luxor-favorite-trip": "Twoja ulubiona wycieczka!",
      "travel-luxor-duration": "• Czas trwania 1 dzień",
      "travel-luxor-transportation": "• Transport klimatyzowanym autobusem",
      "travel-luxor-entry": "• z wejściem",
      "travel-luxor-water": "• Woda na pokładzie",
      "travel-luxor-book-now": "Zarezerwuj teraz",
      "travel-luxor-more-details": "Więcej szczegółów",
      
      "travel-cairo-title": "Kair",
      "travel-cairo-best-price": "Najlepsza cena za osobę",
      "travel-cairo-price": "70.00 EUR",
      "travel-cairo-card-title": "Podróż do Kairu",
      "travel-cairo-favorite-trip": "Twoja ulubiona wycieczka!",
      "travel-cairo-duration": "• Czas trwania 1 dzień",
      "travel-cairo-transportation": "• Transport klimatyzowanym autobusem",
      "travel-cairo-entry": "• z wejściem",
      "travel-cairo-water": "• Woda na pokładzie",
      "travel-cairo-book-now": "Zarezerwuj teraz",
      "travel-cairo-more-details": "Więcej szczegółów",
      
      "terms_conditions": "Regulamin",
      "privacy_policy": "Polityka prywatności",
      "cookie_policy": "Polityka plików cookie",
      
      "private-luxor-title": "Prywatna podróż do Luksoru",
      "private-luxor-card-title": "Prywatna podróż do Luksoru",
      "private-luxor-favorite-trip": "Twoja ulubiona wycieczka!",
      "private-luxor-duration": "• Czas trwania 1 dzień",
      "private-luxor-transportation": "• Transport klimatyzowanym autobusem",
      "private-luxor-entry": "• z wejściem",
      "private-luxor-water": "• Woda na pokładzie",
      "private-luxor-book-now": "Zarezerwuj teraz",
      "private-luxor-more-details": "Więcej szczegółów",
      
      "private-cairo-title": "Prywatna podróż do Kairu",
      "private-cairo-card-title": "Prywatna podróż do Kairu",
      "private-cairo-favorite-trip": "Twoja ulubiona wycieczka!",
      "private-cairo-duration": "• Czas trwania 1 dzień",
      "private-cairo-transportation": "• Transport klimatyzowanym autobusem",
      "private-cairo-entry": "• z wejściem",
      "private-cairo-water": "• Woda na pokładzie",
      "private-cairo-book-now": "Zarezerwuj teraz",
      "private-cairo-more-details": "Więcej szczegółów",
      
      "TransferAirportTaxiServices": "Transfer z lotniska | Usługi taksówkowe w Hurghadzie",
      "TransferNeedTransportation": "Potrzebujesz transferu na lub z lotniska w Hurghadzie? Prywatny transfer na lotnisko w Hurghadzie lub z lotniska! Zrelaksuj się i zarezerwuj komfortowy pojazd z Albatros Travel. Możesz także zarezerwować minivana lub mały autobus dla rodzin lub grup.",
      "TransferInTime": "Punktualność",
      "TransferSafety": "Bezpieczeństwo",
      "TransferTrustful": "Zaufanie",
      "TransferHighQuality": "Wysoka jakość",
      "TransferWeDriveComfortably": "Zawieziemy Cię komfortowo i bezpiecznie prosto z lotniska do hotelu. Jeśli Twój lot się zmieni lub opóźni, nie martw się, śledzimy to w systemie. Albatros Travel oferuje wygodny i przyjemny transfer z lotniska. Przy wyjściu z lotniska czeka na Ciebie przewodnik z tabliczką z Twoim imieniem. Transfer Albatros to nowoczesna usługa, która zapewnia Tobie i Twoim współtowarzyszom podróży bezstresowy i niedrogi przejazd z lotniska do hotelu i z powrotem.",
      "TransferHowToBook": "Jak zarezerwować transfer z Albatros Travel?",
      "TransferInquiry": "Zapytanie",
      "TransferSendRouteDetails": "Prześlij nam swoją trasę lub dane lotu. Możesz skontaktować się z nami na różne sposoby, np. e-mailem.",
      "TransferContactConfirmation": "Kontakt i potwierdzenie",
      "TransferContactConfirmText": "Skontaktujemy się z Tobą w celu potwierdzenia transferu na lub z lotniska w Hurghadzie.",
      "TransferMeetAtAirport": "Spotkanie na lotnisku",
      "TransferDriverWaiting": "Nasz kierowca będzie czekał z tabliczką z Twoim imieniem. Zaprowadzi Cię do pojazdu.",
      "TransferPayment": "Płatność",
      "TransferPaymentUponPickup": "Płatność odbywa się przy odbiorze.",
      
      "TransferAirportHurghadaToHurghada": "Transfer z lotniska w Hurghadzie do Hurghady",
      "TransferPriceFrom20": "Cena od 20 EUR",
      "TransferAirportHurghadaToGouna": "Transfer z lotniska w Hurghadzie do El Gouny",
      "TransferPriceFrom25": "Cena od 25 EUR",
      "TransferAirportHurghadaToMakadi": "Transfer z lotniska w Hurghadzie do Makadi",
      "TransferAirportHurghadaToSahlHasheesh": "Transfer z lotniska w Hurghadzie do Sahl Hasheesh",
      "TransferAirportHurghadaToSomaBay": "Transfer z lotniska w Hurghadzie do Soma Bay",
      "TransferPricesPrivateAirportTransfer": "Ceny prywatnych transferów z lotniska w Hurghadzie",
      "TransferFromHurghadaAirportTo": "Z lotniska w Hurghadzie do",
      "TransferPricePerVehicle": "Cena za pojazd",
      "TransferToHurghada": "Hurghada",
      "TransferToGouna": "El Gouna",
      "TransferToSahlHasheesh": "Sahl Hasheesh",
      "TransferToMakadi": "Makadi",
      "TransferToSomaBay": "Soma Bay",
      "TransferPriceFrom20": "od 20 €",
      "TransferPriceFrom25": "od 25 €",
      "TransferAdvantagesWithAlbatros": "Nasi klienci korzystają z następujących zalet transferów z Albatros Travel:",
      "TransferFixedPrice": "Stała cena",
      "TransferLotsOfVehicles": "Duży wybór pojazdów",
      "TransferComfort": "Komfort",
      "TransferReliability": "Niezawodność",
      "TransferSafety": "Bezpieczeństwo",
      
      "hotelpageCities": "Miasta",
      "hotelpageSubheading": "Zaoszczędź na następnej podróży z ALBATROS TRAVEL. Znajdź świetne oferty na hotele lub apartamenty i zarezerwuj w kilka minut.",
      "hotelpageHurghada": "Hurghada",
      "hotelpageAboutUs": "O nas",
      "hotelpageMission": "ALBATROS TRAVEL – TWOJE SZCZĘŚCIE NASZĄ MISJĄ",
      "hotelpageVacationPlanning": "Planujesz wakacje? Niech ALBATROS TRAVEL będzie Twoim pierwszym przystankiem. Odkryj nasz świat niesamowitych kurortów i wycieczek w Hurghadzie.",
      "hotelpageExperience": "Każdy pobyt z ALBATROS TRAVEL to doświadczenie jak żadne inne. Twórz wspomnienia, które przetrwają całe życie, podróżując z nami po lądzie lub wodzie. Zapewniamy, że przekroczymy Twoje oczekiwania. Obiecujemy powrót, aby stworzyć kolejne szczęśliwe wspomnienia.",
      "hotelpageWelcome": "Witamy w naszej firmie! Jesteśmy Twoim punktem kontaktowym do rezerwacji hoteli i różnych wycieczek w pięknym mieście Hurghada. Z pasją do podróży i zaangażowaniem w wyjątkową obsługę dążymy do tego, aby Twój pobyt w Hurghadzie był niezapomniany.",
      "hotelpageContactUs": "Dołącz do wielkiej rodziny ALBATROS TRAVEL. Nie wahaj się z nami skontaktować. Zarezerwuj już teraz swój kolejny cel podróży.",
      "hotelpageValues": "Nasze wartości można podsumować następująco:",
      "hotelpageToursInEgypt": "Wycieczki po Egipcie",
      "hotelpageVarietyOfTours": "Oferujemy szeroki wybór wycieczek z różnymi trasami po Egipcie.",
      "hotelpageIndividualDayTrips": "Indywidualne wycieczki jednodniowe z:",
      "hotelpageLuxuryNileCruises": "Luksusowe rejsy po Nilu między:",
      "hotelpageLookingForward": "Cieszymy się, że możemy pokazać Ci ‚nasz‘ Egipt!",
      "hotelpageOver20Years": "Od ponad 20 lat stale rozwijamy się i staliśmy się jednym z największych organizatorów wycieczek w Egipcie.",
      "hotelpageOpenToChanges": "Jesteśmy otwarci na nowe zadania, zmiany i wyzwania, i rośniemy razem z nimi.",
      "hotelpagePhilosophy": "Nasza filozofia",
      "hotelpageGuestSatisfaction": "Nasi goście powinni być zadowoleni:",
      "hotelpageFriendlyAdvice": "Doradzamy naszym gościom życzliwie, uczciwie i uprzejmie.",
      "hotelpageCompetence": "Stale rozwijamy nasze kompetencje i oddajemy je do dyspozycji naszych gości.",
      "hotelpageLongTermSatisfaction": "Krótkoterminowy sukces finansowy nie jest dla nas najważniejszy, ale chcemy, aby nasi goście byli długoterminowo zadowoleni, zawsze widzieli w nas partnera i polecali nas innym.",
      
      "parasailingTitle": "Parasailing w Hurghadzie",
      "singleParasailingTitle": "Parasailing pojedynczy",
      "doubleParasailingTitle": "Parasailing podwójny",
      "bestPriceForPerson": "Najlepsza cena za osobę",
      "bestPriceForTwo": "Najlepsza cena za 2 osoby",
      "yourFavouriteTrip": "Twoja ulubiona wycieczka!",
      "pickupDropoff": "• Odbiór i dowóz do hotelu",
      "parasailingDetails": "• Parasailing (10 min w powietrzu)",
      "lifeJacket": "• Kamizelka ratunkowa",
      "speedBoat": "• Szybka łódź",
      "bookNow": "Zarezerwuj teraz",
      
      "fly_board_title": "Flyboard w Hurghadzie",
      "fly_board_caption": "Flyboard",
      "best_price": "Najlepsza cena za osobę",
      "your_favourite_trip": "Twoja ulubiona wycieczka!",
      "fly_board_details_1": "• Flyboard (15 min w powietrzu)",
      "fly_board_details_2": "• Kamizelka ratunkowa",
      "fly_board_details_3": "• Szybka łódź",
      "book_now": "Zarezerwuj teraz",
      
      "in_water_title": "W wodzie",
      
        "banana_boat_title": "Banana Boot",
        "banana_boat_details_1": "• Czas trwania: 15 min",
        "banana_boat_details_2": "• Kamizelka ratunkowa",
        "banana_boat_details_3": "• 10 EUR/os. jeśli jesteście 3 osoby",
        "sofa_bed_title": "Sofa-Łódka",
        "sofa_bed_details_1": "• Czas trwania: 15 min",
        "sofa_bed_details_2": "• Kamizelka ratunkowa",
        "sofa_bed_details_3": "• 10 EUR/os. jeśli jesteście 3 osoby",
        "diving_title": "Nurkowanie",
        "diving_island_title": "Nurkowanie + Wyspa",
        "best_price": "Najlepsza cena za osobę",
        "favourite_trip": "Twoja ulubiona wycieczka dla początkujących",
        "duration_15_min": "• Czas trwania: 15 min / 1 nurkowanie",
        "snorkelling_equipment": "• 2 nurkowania z rurką + sprzęt",
        "soft_drinks_launch": "• Napoje bezalkoholowe + lunch na łodzi",
        "book_now": "Zarezerwuj teraz",
        "daily_diving_title": "Codzienne nurkowanie",
        "duration_1_hour": "• Czas trwania: 1 godzina / nurkowanie",
        "open_water_advanced_title": "Kurs Open Water & Advanced PADI",
        "open_water_diver_course_title": "Kurs Open Water Diver",
        "advanced_diver_course_title": "Kurs zaawansowanego nurka",
        "duration_3_days": "• Czas trwania: 3 dni",
        "first_pool_beach": "• Pierwszy: basen + plaża",
        "second_by_boat": "• Drugi: 2 nurkowania z łodzi",
        "last_dive_exam": "• Ostatni: 1 nurkowanie + egzamin",
        "including_certificate": "• Wliczony certyfikat PADI",
        "your_favourite_trip": "Twoja ulubiona wycieczka!",
        "private_speed_boat_title": "Prywatna motorówka",
        "hours_with_boat": "• 3 godziny łodzią",
        "snorkelling_equipments": "• Nurkowanie z rurką + sprzęt",
        "soft_drinks_fruit": "• Napoje bezalkoholowe + owoce na łodzi",
        "dolphin_house": "• Dom delfinów",
        "more_details": "Więcej szczegółów",
        "full_description": "Pełny opis",
        "day_dives": "1 dzień – 2 nurkowania",
        "explore_red_sea": "Odkryj piękno Morza Czerwonego i zachwyć się jego wspaniałym światem morskim.",
        "tour_details": "Szczegóły wycieczki",
        "tour_day_description": "Dzień na pokładzie z dwoma nurkowaniami i przewodnikiem. Czas na lunch pomiędzy nurkowaniami. Istnieje możliwość wypożyczenia sprzętu.",
        "highlights": "Najważniejsze punkty",
        "dolphin_house_dive_site": "Miejsce nurkowe Dom Delfinów",
        "includes": "W cenie",
        "food_beverages": "Jedzenie i napoje na pokładzie: lunch, kawa, herbata, woda i napoje bezalkoholowe gratis",
        "dive_instructor": "Instruktor nurkowania",
        "transfer_hotel": "Transfer z/do hotelu gratis",
        "excludes": "Nie obejmuje",
        "dive_equipment_rental": "Wynajem sprzętu do nurkowania: 15 €",
        "equipment": "Sprzęt",
        "diving_mask": "Maska do nurkowania (szkło hartowane, nie plastik) z fajką",
        "fins": "Płetwy (zamknięte lub z otwartą piętą + buty)",
        "bcd": "Kamizelka wypornościowa (BCD) z inflatorem",
        "regulator": "Automat oddechowy z manometrem (SPG)",
        "compass_signal_tube": "Kompas i bojka sygnalizacyjna (DSMB)",
        "exposure_suit": "Pianka (w zależności od temperatury wody)",
        "weights": "Obciążniki",
        "weight_belt": "Pas balastowy",
        "aluminium_tank": "Butla aluminiowa",
        "course_overview": "PRZEGLĄD KURSU",
        "scuba_diving_lessons": "Jeśli zawsze chciałeś/aś wziąć lekcje nurkowania i przeżyć niezapomnianą przygodę, zacznij tutaj. Zdobądź certyfikat nurkowy z kursem PADI Open Water Diver – najpopularniejszym i najbardziej uznanym kursem nurkowym na świecie.",
        "millions_scuba_divers": "Miliony ludzi nauczyły się nurkować i odkryły cuda świata wodnego dzięki temu kursowi. Kurs PADI Open Water Diver składa się z trzech głównych etapów: nauki teorii, nurkowań w ograniczonym akwenie, aby opanować podstawowe umiejętności, oraz nurkowań na otwartych wodach, aby je wykorzystać i odkrywać.",
        "whats_included": "Co jest wliczone",
        "padi_materials": "Materiały kursowe PADI i certyfikacja",
        "transfer_hurghada": "Transfer z/do dowolnego hotelu w Hurghadzie",
        "full_diving_equipment": "Pełny sprzęt do nurkowania",
        "whats_excluded": "Czego nie obejmuje",
        "transfer_elgouna": "Transfer z/do hoteli w El Gouna, Sahl Hasheesh, Makadi Bay i Soma Bay 10 € (osoba/dzień)",
        "learning_materials": "Materiały szkoleniowe",
        "choose_material": "Masz dwie opcje wyboru materiałów w różnych językach:",
        "book_option": "Książka: PADI Open Water Diver Manual (książka, RDP i podręcznik RDP) + 5 filmów (do obejrzenia w naszym centrum nurkowym). Oba muszą być ukończone przed zakończeniem kursu.",
        "elearning_option": "eLearning: PADI eLearning umożliwia rozpoczęcie kursu online jeszcze przed urlopem. Zacznij czytać i oglądać filmy przed pierwszym nurkowaniem. Dostęp przez aplikację PADI lub przeglądarkę na dowolnym urządzeniu. Nasz instruktor PADI zaplanuje z Tobą czas na omówienie postępów i upewnienie się, że rozumiesz kluczowe informacje o nurkowaniu.",
        "speed_boat_specifications": "Specyfikacja motorówki",
        "speed_boat_description": "Motorówka to 9-metrowa łódź RIB (sztywna dmuchana), zaprojektowana specjalnie do nurkowania, o maksymalnej pojemności 8 nurków. Wyposażona w dwa silniki Yamaha 115 KM, pozwala dotrzeć do miejsc nurkowych w Hurghadzie w kilka minut. Konstrukcja zapewnia stabilność nawet na wzburzonym morzu, a lekkie wykonanie umożliwia komfortowe manewrowanie.",
        "trip_durations": "Półdniowe wyjazdy motorówką: 1 nurkowanie – 2h, 2 nurkowania – 4h, 3 nurkowania – 6h",
        "emergency_ready": "Gotowość awaryjna",
        "communication_device": "Urządzenie komunikacyjne",
        "gps": "GPS",
        "life_jackets": "Kamizelki ratunkowe",
        "first_aid_kit": "Apteczka pierwszej pomocy",
        "oxygen_supply": "100% tlen",
        "why_dive_speed_boat": "Dlaczego nurkować motorówką?",
        "top_dive_sites": "Najlepsze miejsca nurkowe w pierwszej kolejności",
        "fast_trip": "Szybka podróż (oszczędność czasu)",
        "drift_dive": "Planowanie zawsze z prądem (drift)",
        "citytourhurghada_hurghada": "Hurghada",
        "citytourhurghada_save_on_trip": "Oszczędź na następnej podróży z ALBATROS TRAVEL. Znajdź świetne oferty hoteli lub apartamentów i zarezerwuj w kilka minut.",
        "citytourhurghada_card_title": "Hurghada",
        "citytourhurghada_best_price": "Najlepsza cena za osobę",
        "citytourhurghada_price": "25 EUR",
        "citytourhurghada_guided_tour": "Wycieczka z przewodnikiem",
        "citytourhurghada_tour_description": "Zwiedzanie Hurghady i Muzeum Narodowego z odbiorem i odwiezieniem",
        "citytourhurghada_duration": "• 4 - 5 godzin",
        "citytourhurghada_small_group": "• Mała grupa",
        "citytourhurghada_round_trip": "• Przejazd w obie strony",
        "citytourhurghada_largest_mosque": "• Zwiedzanie największego meczetu",
        "citytourhurghada_largest_church": "• Największy kościół",
        "citytourhurghada_old_city": "• Stare miasto",
        "citytourhurghada_shisha": "• Shisha + 5 EUR extra (rodzaj fajki wodnej)",
        "citytourhurghada_book_now": "Zarezerwuj teraz",
        "citytourhurghada_more_details": "Więcej szczegółów",
        "citytourhurghada_mini_park_title": "Mini Park Egipt to otwarta przestrzeń prezentująca miniaturowe budowle i modele.",
        "citytourhurghada_mini_park_description": "Mini Egypt Park oferuje zupełnie inne doświadczenie w porównaniu do tradycyjnego muzeum. To fantastyczna wycieczka dla turystów, która pełni rolę żywego katalogu atrakcji Egiptu i ułatwia wybór miejsc do zwiedzania. To również świetna opcja dla rodzin z dziećmi i edukacyjne środowisko dla szkół. Nie jest to hobby wyłącznie dla dzieci, lecz także dla dorosłych. Chcemy, aby dzieci odwiedzały to miejsce z dorosłymi. Nowa generacja dorosłych studentów powinna rozwijać to hobby, które przyniesie im korzyści w życiu codziennym. Muzeum miniatur jest bardzo urocze i nie należy lekceważyć jego wartości artystycznej. Obecna kolekcja liczy 60 dzieł sztuki wybranych artystów. Wszystkie powstały jako darowizny przekazywane przez lata. Każde dzieło ma swoją historię i trafiło do Mini Egypt Park. Podczas wizyty przewodnik oprowadzi Cię po całym kraju w kilka godzin – od Kairu po Luksor, od świątyni Abu Simbel i tamy w Asuanie, przez świątynię Edfu i Karnak aż po piramidy w Gizie i Sfinksa.",
        "modalhurghadapage_title": "Prywatne zwiedzanie Hurghady",
        "modalhurghadapage_intro": "Chcesz poznać prawdziwą, oryginalną Hurghadę? Zwiedzić atrakcje miasta? Masz dość masowej turystyki i zwykłych wycieczek? Chcesz zobaczyć, zachwycić się i naprawdę cieszyć?",
        "modalhurghadapage_mix": "Przygotowaliśmy dla Ciebie odpowiednią mieszankę. Oczywiście możesz też spersonalizować swoją wycieczkę! Zwiedzanie Hurghady z Memnon Reisen to alternatywa dla masowej turystyki!",
        "modalhurghadapage_program": "Program prywatnego zwiedzania Hurghady",
        "modalhurghadapage_mosque": "Meczet El Mina Masjid",
        "modalhurghadapage_cathedral": "Katedra koptyjska św. Shenoudy",
        "modalhurghadapage_fishmarket": "Targ rybny",
        "modalhurghadapage_vegetablemarket": "Targ warzywny",
        "modalhurghadapage_marina": "Bulwar Hurghada Marina",
        "modalhurghadapage_description": "Opis prywatnego zwiedzania Hurghady",
        "modalhurghadapage_pickup": "O 14:00 odbierzemy Cię komfortowym klimatyzowanym pojazdem.",
        "modalhurghadapage_firststop": "Pierwszy przystanek to najwyższy punkt miasta. Roztacza się stąd piękny widok panoramiczny na całe miasto Hurghada i Morze Czerwone.",
        "modalhurghadapage_pier": "Następnie pojedziemy na molo. Zachwyć się pięknymi jachtami i atmosferą portu spacerując wzdłuż nabrzeża. Potem odwiedzimy targ rybny, a kolejny przystanek to najstarszy kościół w mieście i największy meczet.",
        "modalhurghadapage_vegetablefruitmarket": "Następnie pojedziemy na targ owocowo-warzywny w Starym Mieście. Później zatrzymamy się w lokalnej kawiarni, aby wypić miętową herbatę lub egipską kawę.",
        "modalhurghadapage_specialrequest": "Jeśli masz specjalne życzenia, możesz to omówić z naszym przewodnikiem. Zatrzymamy się w każdym interesującym miejscu.",
        "modalhurghadapage_backtime": "Około godziny 19:00 odwieziemy Cię do hotelu.",
        "modalhurghadapage_thrilling": "Nasza wycieczka po Hurghadzie będzie niezwykle ekscytująca i zabierzesz ze sobą wiele nowych doświadczeń.",
        "modalhurghadapage_included_services": "Usługi wliczone w cenę",
        "modalhurghadapage_pickup_hotel": "Odbiór z lobby hotelowego",
        "modalhurghadapage_guide": "Przewodnik mówiący po angielsku",
        "modalhurghadapage_support": "Obsługa klienta dostępna 24/7",
        "modalhurghadapage_insurance": "Ubezpieczenie w cenie",
        "modalhurghadapage_prices": "Cennik",
        "modalhurghadapage_table_header1": "Liczba osób",
        "modalhurghadapage_table_header2": "Pojazd",
        "modalhurghadapage_table_header3": "Cena za osobę dorosłą",
        "modalhurghadapage_price1": "1-2 osoby",
        "modalhurghadapage_vehicle1": "Samochód prywatny",
        "modalhurghadapage_price_value1": "35 € /os.",
        "modalhurghadapage_price2": "3-4 osoby",
        "modalhurghadapage_vehicle2": "Minibus prywatny",
        "modalhurghadapage_price_value2": "24 € /os.",
        "modalhurghadapage_price3": "5-6 osób",
        "modalhurghadapage_vehicle3": "Minibus prywatny",
        "modalhurghadapage_price_value3": "19 € /os.",
        "modalhurghadapage_price4": "7-8 osób",
        "modalhurghadapage_vehicle4": "Minibus prywatny",
        "modalhurghadapage_price_value4": "13 € /os.",
        "modalhurghadapage_table_duration": "Czas trwania",
        "modalhurghadapage_table_trip_type": "Rodzaj wycieczki",
        "modalhurghadapage_table_availability": "Dostępność",
        "modalhurghadapage_table_pickup_time": "Godzina odbioru",
        "modalhurghadapage_duration": "ok. 6 godzin",
        "modalhurghadapage_trip_type": "Indywidualna",
        "modalhurghadapage_availability": "Codziennie",
        "modalhurghadapage_pickup_time_value": "ok. 14:00",
        "modalhurghadapage_orangebay_title": "ORANGE BAY",
        "modalhurghadapage_orangebay_price": "Najlepsza cena za osobę",
        "modalhurghadapage_orangebay_price_value": "25,00 EUR",
        "modalhurghadapage_orangebay_subtitle": "Orange Bay",
        "modalhurghadapage_orangebay_favorite_trip": "Twoja ulubiona wycieczka!",
        "modalhurghadapage_orangebay_duration": "Czas trwania 7 - 8 godzin",
        "modalhurghadapage_orangebay_snorkelling": "Nurkowanie z rurką + sprzęt",
        "modalhurghadapage_orangebay_food_drinks": "Napoje bezalkoholowe i gorące + lunch w formie bufetu na łodzi",
        "modalhurghadapage_orangebay_pickup": "Odbiór i powrót do hotelu",
      
      "modalhurghadapage_orangebay_booknow": "Zarezerwuj teraz",
      "modalhurghadapage_orangebay_moredetails": "Więcej szczegółów",
      "boattrips_edenisland_title": "Wyspa Eden",
      "boattrips_best_price": "Najlepsza cena za osobę",
      "boattrips_edenisland_price": "65,00 EUR",
      "boattrips_edenisland_title_small": "Wyspa Eden",
      "boattrips_favourite_trip": "Twoja ulubiona wycieczka!",
      "boattrips_duration": "• Czas trwania 7 - 8 godzin",
      "boattrips_snorkelling": "• Nurkowanie z rurką + sprzęt",
      "boattrips_drinks_and_lunch": "• Napoje bezalkoholowe i gorące oraz lunch w formie bufetu na łodzi",
      "boattrips_pickup": "• Odbiór i powrót do hotelu",
      "boattrips_book_now": "Zarezerwuj teraz",
      "boattrips_more_details": "Więcej szczegółów",
      
      "boattrips_mahmyaisland_title": "Wyspa Mahmya",
      "boattrips_mahmyaisland_price": "75,00 EUR",
      "boattrips_mahmyaisland_title_small": "Wyspa Mahmya",
      
      "boattrips_aquarium_title": "Akwarium",
      "boattrips_aquarium_price": "30,00 EUR",
      "boattrips_aquarium_title_small": "Akwarium",
      "boattrips_duration_short": "• Czas trwania 2 godziny",
      "boattrips_entry": "• Wstęp",
      "boattrips_transfer": "• Transfer dostępny",
      
      "boattrips_dolphinworld_title": "Świat delfinów",
      "boattrips_dolphinworld_price": "15,00 EUR",
      "boattrips_dolphinworld_title_small": "Świat delfinów",
      "boattrips_duration_medium": "• Czas trwania 1,5 - 2 godziny",
      "boattrips_swim_with_dolphin": "• Pływanie z delfinami nie wliczone ... Prywatna cena za pływanie z delfinami",
      "boattrips_video_pictures": "• Dostępne wideo i zdjęcia",
      
      "boattrips_submarine_title": "Łódź podwodna",
      "boattrips_royal_submarine_title": "Królewska łódź podwodna Sea Scoupe",
      "boattrips_best_price": "Najlepsza cena za osobę",
      "boattrips_royal_submarine_price": "15,00 EUR",
      "boattrips_royal_submarine_title_small": "Królewska łódź podwodna Sea Scoupe",
      "boattrips_favourite_trip": "Twoja ulubiona wycieczka!",
      "boattrips_pickup_times_royal": "• Odbiór o 10:00, 11:00 i 15:00",
      "boattrips_transfer": "• Transfer",
      "boattrips_welcome_drink": "• Powitalny napój",
      "boattrips_free_snorkeling": "• W cenie 30 minut darmowego nurkowania z rurką",
      "boattrips_swimming_equipment": "• Sprzęt do pływania (maska, płetwy, kamizelka ratunkowa)",
      
      "boattrips_sindbad_submarine_title": "Łódź podwodna Sindbad",
      "boattrips_sindbad_submarine_price": "40,00 EUR",
      "boattrips_sindbad_submarine_title_small": "Łódź podwodna Sindbad",
      "boattrips_pickup_times_sindbad": "• Godziny rozpoczęcia: 09:00, 11:00, 13:00, 15:00",
      "boattrips_dive_depth": "• Nurkowanie do 25 metrów przez około 25 minut",
      "boattrips_english_speakers": "• Przewodnicy mówiący po angielsku",
      "boattrips_hurghada_transport": "• Usługa transportowa w Hurghadzie",
      
      "boattrips_glassboat_title": "Prywatna łódź ze szklanym dnem",
      "boattrips_glassboat_price": "100,00 EUR",
      "boattrips_glassboat_title_small": "Prywatna łódź ze szklanym dnem",
      "boattrips_duration": "• Czas trwania - 3 godziny",
      "boattrips_life_jacket": "• Kamizelka ratunkowa",
      "boattrips_snorkeling_equipment": "• Sprzęt do nurkowania z rurką",
      "boattrips_book_now": "Zarezerwuj teraz",
      
      "fish_trip_title": "Rejs wędkarski łodzią",
      "fish_trip_caption_title": "Rejs wędkarski",
      "fish_trip_caption_subtitle": "Najlepsza cena za osobę",
      "fish_trip_card_title": "Rejs wędkarski",
      "fish_trip_card_description": "Twoja ulubiona wycieczka!",
      "fish_trip_details_1": "• Rejs wędkarski od 8:30 do 16:00 tylko w piątek",
      "fish_trip_details_2": "• Transfer z hotelu do portu i z powrotem",
      "fish_trip_details_3": "• Transfer klimatyzowanym pojazdem",
      "fish_trip_details_4": "• Ekscytujący rejs wędkarski w Hurghadzie",
      "fish_trip_details_5": "• Cały sprzęt wędkarski i do nurkowania",
      "fish_trip_details_6": "• Rejs łodzią",
      "fish_trip_details_7": "• Przewodnik mówiący po angielsku",
      "fish_trip_details_8": "• Dwa postoje wędkarskie",
      "fish_trip_details_9": "• Obfity lunch",
      "fish_trip_details_10": "• Dwa postoje wędkarskie",
      "fish_trip_details_11": "• Kamizelka ratunkowa",
      
      "fish_trip_book_now": "Zarezerwuj teraz",
      "fish_trip_more_details": "Więcej szczegółów",
      "close_button": "Zamknij",
      "program_title": "Program wycieczki snorkelingowej na Orange Bay Hurghada",
      "snorkeling_stops": "2 przystanki na snorkeling",
      "orange_bay_stop": "2 godziny pobytu na wyspie Orange Bay",
      "lunch": "Obiad",
      "banana_ride": "Przejażdżka na bananie",
      "schedule_title": "Harmonogram wycieczki snorkelingowej na Orange Bay Hurghada",
      "time": "Czas",
      "program": "Program",
      "pickup_hotel": "Odbiór z hotelu",
      "takeoff_orange_bay": "Wypłynięcie na Orange Bay",
      "return_port": "Powrót do portu",
      "departure_hotel": "Wyjazd do hotelu",
      "back_hotel": "Powrót do hotelu",
      "description_title": "Opis wycieczki snorkelingowej na Orange Bay Hurghada",
      "pickup_description": "Około godziny 8:30 odbierzemy Cię z hotelu i zawieziemy na molo. Na luksusowo wyposażonej łodzi popłyniemy na wyspę Orange Bay.",
      "snorkel_coral": "Podczas wycieczki będziesz nurkować z rurką przy pięknych rafach koralowych. Następnie mała łódź przewiezie Cię na wyspę Orange Bay.",
      "two_hours": "Spędzisz około 2 godzin na wyspie Orange Bay. Zrelaksuj się na pięknej piaszczystej plaży lub nurkuj wokół wyspy.",
      "lunch_boat_trip": "Opuszczamy wyspę i płyniemy łodzią, aby zjeść obiad, a następnie kontynuujemy drugą przygodę snorkelingową.",
      "return_pier": "Około godziny 16:00 wrócimy na molo, gdzie będzie czekał kierowca, aby zawieźć nas z powrotem do hotelu.",
      "boattrips_close": "Zamknij",
      "boattrips_program_title": "Wycieczka snorkelingowa na wyspę Mahmya Hurghada",
      "boattrips_snorkeling": "Snorkeling na wyspie Mahmya",
      "boattrips_lunch": "Obiad",
      "boattrips_description_title": "Opis wycieczki snorkelingowej na wyspę Mahmya Hurghada",
      "boattrips_pickup_description": "Rano odbierzemy Cię z hotelu i zawieziemy na molo. Na pokładzie powita Cię przyjazna załoga, która zapewni sprzęt do snorkelingu (maska i płetwy) na ekscytującą przygodę. Zanurz się w dziewiczym podwodnym świecie i odkryj wiele miejsc do snorkelingu!",
      "boattrips_sail_red_sea": "Wypłyń na Morze Czerwone, gdzie kapitan obierze kurs na wyspę Mahmya. Po przybyciu zejdziesz na ląd, aby odkrywać malowniczą wyspę i unikalny krajobraz. Następnie zjesz obfity lunch w restauracji nad wodą.",
      "boattrips_after_lunch": "Po lunchu na wyspie Mahmya będziesz mieć okazję do snorkelingu w lazurowej wodzie lub spaceru po plaży. Ciesz się słońcem, białym piaskiem i od czasu do czasu popływaj w Morzu Czerwonym. Podziwiaj naturalne piękno, turkusowe morze i idylliczną wyspę.",
      "boattrips_return_port": "Po niesamowitej wycieczce na wyspę Mahmya Hurghada wrócisz późnym popołudniem do portu, skąd zostaniesz przewieziony z powrotem do hotelu.",
      "boattrips_program_titledolphin": "Dom delfinów – snorkeling i pływanie z delfinami",
      "boattrips_dolphins_description": "Delfiny zazwyczaj wyglądają tak uroczo, skaczą radośnie w morzu i zawsze są w dobrym nastroju. Wycieczka do delfinów to wspaniałe przeżycie, a pływanie z nimi to marzenie wielu turystów w Hurghadzie. Memnon Reisen sprawia, że to możliwe.",
      "boattrips_discover_red_sea": "Odkryj tajemniczy świat Morza Czerwonego! Nurkuj z rurką i pływaj z dzikimi delfinami na otwartym morzu w Hurghadzie.",
      "boattrips_relax_boat": "Zrelaksuj się na łodzi i podziwiaj malownicze krajobrazy! Ciesz się nieskończonymi kolorami i formami ryb na magicznej rafie koralowej!",
      "boattrips_program_schedule_title": "Program snorkelingu i pływania z delfinami w Domu Delfinów",
      "boattrips_program_list": "Program",
      "boattrips_swim_with_dolphins": "Pływanie z delfinami",
      "boattrips_snorkeling": "Snorkeling",
      "boattrips_lunch": "Obiad",
      "boattrips_schedule_title": "Harmonogram snorkelingu i pływania w Domu Delfinów",
      "boattrips_time": "Czas",
      "boattrips_program": "Program",
      "boattrips_pickup_time": "⏰ 8:00",
      "boattrips_pickup_description": "Odbiór z hotelu",
      "boattrips_takeoff_time": "⏰ 9:00",
      "boattrips_takeoff": "Wypłynięcie",
      "boattrips_arrival_time": "⏰ 15:30",
      "boattrips_arrival_description": "Powrót do Hurghady",
      "boattrips_departure_time": "⏰ 15:45",
      "boattrips_departure_description": "Wyjazd do hotelu",
      "boattrips_back_time": "⏰ 16:30",
      "boattrips_back_description": "Powrót do hotelu",
      "boattrips_description_title": "Opis snorkelingu i pływania z delfinami w Domu Delfinów",
      "boattrips_pickup_time_description": "Między 7:00 a 8:00 (w zależności od lokalizacji hotelu) odbierzemy Cię klimatyzowanym pojazdem i zawieziemy na przystań. Powita Cię kapitan i załoga.",
      "boattrips_excursion_description": "Podczas wycieczki zatrzymamy się w trzech różnych miejscach, gdzie będziesz mógł pływać lub nurkować z rurką. Zobaczysz szczęśliwe, figlarne delfiny z bliska.",
      "boattrips_lunch_time": "O 13:00 załoga poda pyszny obiad.",
      "boattrips_return_time_description": "Po południu wrócimy na przystań, a stamtąd do hotelu. Około 15:30 będziesz z powrotem w hotelu.",
      "boattrips_excursion_experience": "Wycieczka do delfinów to jedno z najwspanialszych morskich doświadczeń, jakie możesz przeżyć.",
      "boattrips_fishing_trip_title": "Rejs wędkarski łodzią – wędkowanie na Morzu Czerwonym w Hurghadzie z trzema postojami",
      "boattrips_experience_title": "Doświadczenie",
      "boattrips_experience_description": "Przeżyj ekscytującą wycieczkę łodzią z Hurghady. Masz możliwość wędkowania w trzech różnych miejscach na otwartym morzu.",
      "boattrips_experience_pickup": "Po śniadaniu odbierzemy Cię klimatyzowanym pojazdem z hotelu i zawieziemy bezpośrednio na łódź wędkarską.",
      "boattrips_fishing_title": "Wędkowanie",
      "boattrips_fishing_description": "Masz trzy postoje na wędkowanie na otwartym morzu. Jeśli nie masz ochoty łowić, możesz zrelaksować się na pokładzie lub popływać. Jeśli złowisz jadalną rybę, nasz kucharz przygotuje ją od razu na łodzi!",
      "boattrips_types_of_fish_title": "Gatunki ryb",
      "boattrips_fish_tuna": "Tuńczyk",
      "boattrips_fish_sailfish": "Żaglica",
      "boattrips_fish_grouper": "Granik",
      
      "boattrips_fishing_trip_hurghada_title": "Wyprawa wędkarska w Hurghadzie",
      "boattrips_fishing_trip_hurghada_description": "Morze Czerwone ma jednak o wiele więcej do zaoferowania. Dla profesjonalnego wędkarza Hurghada jest jednym z wymarzonych miejsc na świecie.",
      "boattrips_fishing_trip_hurghada_experience": "Liczne, ogromne rafy koralowe, które znajdują się niedaleko wybrzeża, są domem dla wielu dużych gatunków ryb. Oprócz wspomnianych już tuńczyków znajdziesz tu także okonie, bonito, a dalej na południu Morza Czerwonego nawet rekiny. Tutaj każdy wędkarz znajdzie coś dla siebie.",
      "boattrips_fishing_trip_hurghada_assistance": "Nie masz jeszcze dużego doświadczenia w wędkarstwie? Nie ma problemu. Oczywiście nasi doświadczeni egipscy rybacy z przyjemnością pomogą Ci i doradzą na pokładzie. Jeśli nie interesuje Cię wyłącznie łowienie ryb, ale chcesz także cieszyć się różnorodnością fauny i morzem – jesteś we właściwym miejscu.",
      "boattrips_accompanying_persons_title": "Osoby towarzyszące",
      "boattrips_accompanying_persons_description": "Osoby towarzyszące, które nie chcą łowić ryb, mogą oczywiście odpocząć na pokładzie statku lub wybrać się na snorkeling; pobliskie rafy są do tego idealne. Jeśli złapiesz jadalną rybę, doświadczeni kucharze na pokładzie chętnie przygotują ją na miejscu.",
      "boattrips_included_title": "Co jest wliczone",
      "boattrips_included_transfers": "Transfery z/do hotelu wysokiej jakości klimatyzowanymi pojazdami",
      "boattrips_included_fishing_trip": "Rejs wędkarski łodzią z trzema przystankami",
      "boattrips_included_snorkeling_equipment": "Sprzęt do snorkelingu",
      "boattrips_included_guide_assistance": "Pomoc przewodnika",
      "boattrips_included_lunch": "Obiad na pokładzie łodzi",
      "boattrips_included_drinks": "Woda mineralna i napoje bezalkoholowe",
      "boattrips_not_included_title": "Co nie jest wliczone",
      "boattrips_not_included_tips": "Napiwki dla przewodników i transfer z Makadi Bay, El Gouna 10 euro za osobę",
      "boattrips_not_included_personal_items": "Przedmioty osobiste, posiłki, napoje lub usługi, które nie zostały wymienione",
      
      "elgouna_section_heading": "El Gouna",
      "elgouna_section_subheading": "Oszczędzaj podczas swojej następnej podróży z ALBATROS TRAVEL. Znajdź świetne oferty hoteli lub apartamentów i zarezerwuj w zaledwie kilka minut.",
      "elgouna_private_tour_program_title": "Program prywatnej wycieczki po El Gouna",
      "elgouna_private_tour_program_items0": "• Rejs po lagunie",
      "elgouna_private_tour_program_items1": "• Wieża El Gouna",
      "elgouna_private_tour_program_items2": "• Centrum El Gouna",
      "elgouna_private_tour_program_items3": "• Abu Tig Marina (El Gouna)",
      "elgouna_book_now": "Zarezerwuj teraz",
      "elgouna_more_details": "Więcej szczegółów",
      
      "modal_table_header_people": "Liczba osób",
      "modal_table_header_car": "Rodzaj samochodu",
      "modal_table_header_price": "Cena za osobę",
      "modal_table_row_2_person": "2 osoby",
      "modal_table_row_private_car": "Samochód prywatny",
      "modal_table_row_price_2": "30 € / os.",
      "modal_table_row_3_4_person": "3-4 osoby",
      "modal_table_row_private_mini_bus": "Prywatny minibus",
      "modal_table_row_price_3_4": "25 € / os.",
      "modal_table_row_5_8_person": "5-8 osób",
      "modal_table_row_private_mini_bus_2": "Prywatny minibus",
      "modal_table_row_price_5_8": "19 € / os.",
      "modal_table_row_10_person": "10 osób",
      "modal_table_row_private_mini_bus_3": "Prywatny minibus",
      "modal_table_row_price_10": "17 € / os.",
      "modal_table_header_duration": "Czas trwania",
      "modal_table_header_trip_type": "Rodzaj wycieczki",
      "modal_table_header_availability": "Dostępność",
      "modal_table_header_pickup_time": "Godzina odbioru",
      "modal_table_row_duration": "ok. 4 godziny",
      "modal_table_row_trip_type": "Indywidualna",
      "modal_table_row_availability": "Codziennie",
      "modal_table_row_pickup_time": "ok. 09:00",
      
      "modal_paragraph_intro": "Prywatna wycieczka po El Gouna to świetna okazja, aby poznać to piękne miasto, prawdziwy europejski cud pośrodku gorącej egipskiej pustyni.",
      "modal_paragraph_city_description": "El Gouna jest sztuczna jak Dubaj i elegancka jak europejskie miasto śródziemnomorskie.",
      "modal_paragraph_charm": "Miasto oczaruje Cię swoją harmonijną architekturą i pięknem błękitnych lagun. To jedno z najbardziej romantycznych miejsc, nazywane także egipską Wenecją.",
      "modal_heading_program": "Program prywatnej wycieczki po El Gouna",
      "modal_list_item_lagoon_trip": "Rejs po lagunie",
      "modal_list_item_el_gouna_tower": "Wieża El Gouna",
      "modal_list_item_el_gouna_downtown": "Centrum El Gouna",
      "modal_list_item_abu_tig_marina": "Abu Tig Marina (El Gouna)",
      "modal_heading_description": "Opis prywatnej wycieczki po El Gouna",
      "modal_paragraph_pickup_info": "Odbierzemy Cię między 9:00 a 10:00 z Twojego hotelu. Dokładna godzina zostanie potwierdzona w zależności od lokalizacji hotelu.",
      "modal_paragraph_boat_info": "Po przybyciu do El Gouna wsiądziesz na łódź wahadłową. Z pewnością będziesz cieszyć się fantastycznym rejsem po lagunie. Rejs po lagunie w El Gouna to obowiązkowy punkt programu!",
      "modal_paragraph_city_tour_info": "Podczas wycieczki po El Gouna przepłyniemy przez lagunę, aby zwiedzić kurort. Zobaczymy wszystkie hotele i różne części miasta oraz morza.",
      "modal_paragraph_downtown_info": "Po przepłynięciu laguny udamy się do centrum. Będziesz mieć czas wolny na zakupy. Zaprosimy Cię również na egipską herbatę w orientalnej kawiarni.",
      "modal_paragraph_marina_info": "Na końcu zrobimy wycieczkę po porcie (Abu Tig Marina), pierwszym prywatnym porcie nad Morzem Czerwonym. Podziwiaj liczne statki i luksusowe jachty z całego świata, które zatrzymują się w El Gouna, zanim wyruszą w podróż na Morze Śródziemne lub Ocean Indyjski.",
      "modal_paragraph_memorable_experience": "Indywidualna wycieczka po El Gouna pozostanie długo w pamięci.",
      
      "list_fair_prices": "Uczciwe ceny",
      "list_high_quality_service": "Wysoka jakość usług",
      "list_flexibility": "Elastyczność",
      "list_time_for_you": "Czas dla Ciebie",
      "list_guided_by_you": "Dostosowujemy się do Ciebie",
      "list_create_your_memories": "Tworzymy Twoje wspomnienia"
      
      
      
      
      



    }
};


// Function to change the language
function changeLanguage(language) {
    // احفظ اللغة المختارة في localStorage
    localStorage.setItem("selectedLanguage", language);

    // غير النصوص في الصفحة
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[language] && translations[language][key]) {
            element.textContent = translations[language][key];
        }
    });
}

document.addEventListener("DOMContentLoaded", function () {
    const savedLang = localStorage.getItem("selectedLanguage") || "en";
    changeLanguage(savedLang);
});

